import { StyleSheet, Platform } from 'react-native';
import { SPACING, TYPOGRAPHY, RADIUS } from '../../constants/theme';

export const getStyles = (colors: any) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    scrollContent: {
        paddingBottom: SPACING.xxl,
    },
    center: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.background,
    },
    header: {
        paddingHorizontal: SPACING.lg,
        paddingTop: Platform.OS === 'ios' ? 0 : SPACING.lg,
        paddingBottom: SPACING.xl,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: SPACING.xl,
    },
    greeting: {
        fontSize: 28,
        fontWeight: '800',
        letterSpacing: -0.5,
        color: colors.text,
    },
    subtitle: {
        fontSize: 15,
        marginTop: 2,
        fontWeight: '500',
        color: colors.textLight,
    },
    iconButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        backgroundColor: colors.surface,
        borderColor: colors.border,
    },
    availabilityCard: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: SPACING.md,
        borderRadius: RADIUS.xl,
        borderWidth: 1,
        borderColor: colors.border,
    },
    availInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        paddingRight: SPACING.md,
    },
    statusIndicator: {
        width: 8,
        height: 8,
        borderRadius: 4,
        marginRight: 10,
    },
    availText: {
        fontSize: 13,
        fontWeight: '600',
        lineHeight: 18,
    },
    statsRow: {
        flexDirection: 'row',
        paddingHorizontal: SPACING.lg,
        gap: SPACING.md,
        marginBottom: SPACING.xl,
    },
    statCard: {
        flex: 1,
        padding: SPACING.md,
        alignItems: 'center',
        gap: 8,
    },
    statIcon: {
        width: 44,
        height: 44,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 4,
    },
    statInfo: {
        alignItems: 'center',
    },
    statLabel: {
        fontSize: 10,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.8,
        textAlign: 'center',
        color: colors.textLight,
    },
    statValue: {
        fontSize: 20,
        fontWeight: '800',
        marginTop: 2,
        color: colors.text,
    },
    mainContent: {
        paddingHorizontal: SPACING.lg,
    },
    section: {
        marginBottom: SPACING.xl * 1.5,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: SPACING.lg,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '800',
        letterSpacing: -0.5,
        color: colors.text,
    },
    badge: {
        fontSize: 10,
        fontWeight: 'bold',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 8,
        overflow: 'hidden',
    },
    serviceCard: {
        marginBottom: SPACING.md,
        padding: 0,
        overflow: 'hidden',
        borderRadius: RADIUS.lg,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: SPACING.lg,
        paddingBottom: SPACING.md,
    },
    categoryInfo: {
        flex: 1,
        paddingRight: SPACING.md,
    },
    categoryTitle: {
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 4,
        color: colors.text,
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    timeText: {
        fontSize: 13,
        fontWeight: '600',
        color: colors.textLight,
    },
    statusBadge: {
        paddingHorizontal: 12,
        paddingVertical: 5,
        borderRadius: RADIUS.full,
        height: 26,
        justifyContent: 'center',
    },
    statusText: {
        fontSize: 10,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    cardBody: {
        paddingHorizontal: SPACING.lg,
        paddingBottom: SPACING.lg,
    },
    detailRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginTop: 6,
    },
    detailText: {
        fontSize: 14,
        fontWeight: '500',
        flex: 1,
        color: colors.text,
    },
    cardFooter: {
        padding: SPACING.md,
        paddingHorizontal: SPACING.lg,
        borderTopWidth: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderTopColor: colors.border,
    },
    footerLink: {
        fontSize: 13,
        fontWeight: '700',
        color: colors.primary,
    },
    emptyCard: {
        alignItems: 'center',
        padding: SPACING.xxl,
        gap: 12,
        borderStyle: 'dashed',
        borderRadius: RADIUS.xl,
    },
    emptyText: {
        fontSize: 14,
        fontWeight: '500',
        color: colors.textLight,
    },
    offlineCard: {
        padding: SPACING.xl,
        alignItems: 'center',
        borderRadius: RADIUS.xl,
        backgroundColor: colors.surface,
    },
    offlineText: {
        fontSize: 14,
        textAlign: 'center',
        lineHeight: 20,
        fontWeight: '600',
        color: colors.textLight,
    },
    requestContent: {
        flexDirection: 'row',
        padding: SPACING.lg,
        gap: 16,
        alignItems: 'center',
    },
    reqMain: {
        flex: 1,
    },
    priceAction: {
        alignItems: 'flex-end',
        justifyContent: 'center',
        gap: 10,
    },
    priceTag: {
        fontSize: 20,
        fontWeight: '900',
        letterSpacing: -0.5,
        color: colors.primary,
    },
    smallBtn: {
        minHeight: 38,
        paddingHorizontal: SPACING.xl,
        borderRadius: RADIUS.lg,
    },
    smallBtnText: {
        fontSize: 14,
        fontWeight: '700',
    },
    reviewItem: {
        padding: SPACING.lg,
        marginBottom: SPACING.md,
        borderRadius: RADIUS.lg,
        borderWidth: 0,
        backgroundColor: colors.surface,
    },
    reviewHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    reviewCategory: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.text,
    },
    reviewStars: {
        flexDirection: 'row',
        gap: 2,
    },
    reviewText: {
        fontSize: 14,
        fontStyle: 'italic',
        lineHeight: 20,
        marginBottom: 8,
        color: colors.textLight,
    },
    reviewDate: {
        fontSize: 11,
        fontWeight: '600',
        color: colors.textMuted,
    }
});
