import { StyleSheet } from 'react-native';
import { SPACING, RADIUS } from '../../constants/theme';

export const getStyles = (colors: any) => StyleSheet.create({
    container: {
        marginBottom: SPACING.xl,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: SPACING.md,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: colors.text,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.surface,
        borderRadius: RADIUS.md,
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm,
        marginBottom: SPACING.md,
        borderWidth: 1,
        borderColor: colors.border,
    },
    searchInput: {
        flex: 1,
        marginLeft: SPACING.sm,
        color: colors.text,
        fontSize: 15,
    },
    filtersRow: {
        flexDirection: 'row',
        marginBottom: SPACING.sm,
    },
    filterChip: {
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.xs,
        borderRadius: RADIUS.full,
        borderWidth: 1,
        borderColor: colors.border,
        marginRight: SPACING.sm,
        backgroundColor: colors.surface,
    },
    filterChipActive: {
        backgroundColor: colors.primary,
        borderColor: colors.primary,
    },
    filterText: {
        fontSize: 13,
        color: colors.textMuted,
        fontWeight: '500',
    },
    filterTextActive: {
        color: '#ffffff',
    },
    workerFlatList: {
        height: 185,
    },
    workerList: {
        paddingRight: SPACING.lg,
        paddingBottom: SPACING.sm,
    },
    workerCard: {
        width: 240,
        backgroundColor: colors.surface,
        borderRadius: RADIUS.lg,
        padding: SPACING.md,
        marginRight: SPACING.md,
        borderWidth: 1,
        borderColor: colors.border,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    workerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: SPACING.sm,
    },
    avatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.primary + '20',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: SPACING.sm,
    },
    workerName: {
        fontSize: 16,
        fontWeight: '600',
        color: colors.text,
    },
    cityContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    cityText: {
        fontSize: 12,
        color: colors.textMuted,
        marginLeft: SPACING.xs,
    },
    bioText: {
        fontSize: 13,
        color: colors.textLight,
        marginBottom: SPACING.md,
        lineHeight: 18,
    },
    workerFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 'auto',
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.warning + '15',
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.xs,
        borderRadius: RADIUS.sm,
    },
    ratingText: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.warning,
        marginLeft: SPACING.xs,
    },
    availableBadge: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: colors.success,
        borderWidth: 2,
        borderColor: '#ffffff',
        position: 'absolute',
        bottom: 0,
        right: 0,
    },
    noResults: {
        padding: SPACING.xl,
        alignItems: 'center',
        justifyContent: 'center',
    },
    noResultsText: {
        color: colors.textMuted,
        fontSize: 15,
        marginTop: SPACING.md,
    },

    // ── Rating Filter Row ──────────────────────────────────────────────────────
    ratingFilterRow: {
        flexDirection: 'column',
        marginBottom: SPACING.md,
        gap: SPACING.sm,
    },
    ratingFilterLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.xs,
    },
    ratingFilterRight: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
    },
    ratingFilterLabel: {
        fontSize: 12,
        color: colors.textMuted,
        fontWeight: '600',
    },
    filterChipSmall: {
        paddingVertical: SPACING.xs,
        paddingHorizontal: SPACING.smd,
        marginRight: SPACING.sm,
    },
    sortToggle: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.xs,
    },
    sortToggleText: {
        fontSize: 12,
        color: colors.primary,
        fontWeight: '700',
    },
    loadingWorkers: {
        height: 160,
        justifyContent: 'center',
        alignItems: 'center',
    },
    errorText: {
        color: colors.danger,
        fontSize: 13,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
    },
    modalContent: {
        backgroundColor: colors.surface,
        borderTopLeftRadius: RADIUS.xxl,
        borderTopRightRadius: RADIUS.xxl,
        maxHeight: '85%',
        paddingTop: SPACING.md,
        borderWidth: 1,
        borderColor: colors.border,
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.15,
        shadowRadius: 10,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: SPACING.lg,
        paddingBottom: SPACING.md,
        borderBottomWidth: 1,
        borderColor: colors.border,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '800',
        color: colors.text,
    },
    closeButton: {
        padding: SPACING.xs,
        borderRadius: RADIUS.full,
        backgroundColor: colors.border + '40',
    },
    modalBody: {
        paddingHorizontal: SPACING.lg,
        paddingTop: SPACING.md,
        paddingBottom: SPACING.xxl,
    },
    profileHero: {
        alignItems: 'center',
        marginBottom: SPACING.lg,
        paddingBottom: SPACING.md,
        borderBottomWidth: 1,
        borderColor: colors.border,
    },
    largeAvatar: {
        width: 96,
        height: 96,
        borderRadius: 48,
        backgroundColor: colors.primary + '15',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: SPACING.md,
    },
    largeAvatarImage: {
        width: 96,
        height: 96,
        borderRadius: 48,
    },
    modalAvailableBadge: {
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: colors.success,
        borderWidth: 3,
        borderColor: colors.surface,
        position: 'absolute',
        bottom: 2,
        right: 2,
    },
    modalWorkerName: {
        fontSize: 22,
        fontWeight: '800',
        color: colors.text,
        textAlign: 'center',
    },
    modalCityRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: SPACING.xs,
        gap: SPACING.xs,
    },
    modalCityText: {
        fontSize: 14,
        color: colors.textLight,
        fontWeight: '500',
    },
    statusTag: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: SPACING.md,
        paddingVertical: 6,
        borderRadius: RADIUS.full,
        marginTop: SPACING.md,
        gap: 6,
    },
    statusTagDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    statusTagText: {
        fontSize: 12,
        fontWeight: '800',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    modalRatingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.primary + '08',
        padding: SPACING.md,
        borderRadius: RADIUS.lg,
        marginBottom: SPACING.lg,
        borderWidth: 1,
        borderColor: colors.primary + '15',
    },
    modalRatingBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.warning + '15',
        paddingHorizontal: SPACING.md,
        paddingVertical: SPACING.sm,
        borderRadius: RADIUS.md,
        gap: SPACING.xs,
    },
    modalRatingValue: {
        fontSize: 18,
        fontWeight: '800',
        color: colors.warning,
    },
    modalRatingTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.text,
    },
    modalRatingSubtitle: {
        fontSize: 12,
        color: colors.textMuted,
        marginTop: 2,
    },
    modalSection: {
        marginBottom: SPACING.lg,
    },
    modalSectionTitle: {
        fontSize: 16,
        fontWeight: '800',
        color: colors.text,
        marginBottom: SPACING.sm,
    },
    modalBioText: {
        fontSize: 14,
        color: colors.textLight,
        lineHeight: 20,
    },
    modalReviewCard: {
        backgroundColor: colors.background,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: RADIUS.md,
        padding: SPACING.md,
        marginBottom: SPACING.sm,
    },
    reviewHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    reviewerName: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.text,
    },
    reviewDateText: {
        fontSize: 11,
        color: colors.textMuted,
    },
    reviewStarsRow: {
        flexDirection: 'row',
        gap: 3,
        marginTop: 4,
        marginBottom: SPACING.xs,
    },
    reviewCommentText: {
        fontSize: 13,
        color: colors.textLight,
        lineHeight: 18,
    },
    emptyReviewsBox: {
        padding: SPACING.lg,
        backgroundColor: colors.background,
        borderRadius: RADIUS.md,
        borderWidth: 1,
        borderColor: colors.border,
        borderStyle: 'dashed',
    },
    emptyReviewsText: {
        fontSize: 13,
        color: colors.textMuted,
        textAlign: 'center',
        lineHeight: 18,
    },
});
