[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install -r Backend/requirements.txt"]

[phases.build]
cmds = [
    "cd Backend && python3 manage.py collectstatic --noinput",
    "cd Backend && python3 manage.py migrate --noinput"
]

[start]
cmd = "cd Backend && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
