# Generated by Django 6.0.2 on 2026-04-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicerequestnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
