# Generated by Django 6.0.2 on 2026-04-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicerequest_is_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestnotification',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
