# Generated by Django 6.0.2 on 2026-03-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(db_index=True, default='Medellín', max_length=100),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='average_rating',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
