# Generated by Django 6.0.2 on 2026-03-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_workerprofile_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='identity_document',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
