# Generated by Django 6.0.2 on 2026-03-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_workerprofile_identity_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='document_back',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='document_front',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verification_status',
            field=models.CharField(choices=[('NONE', 'Sin iniciar'), ('PENDING', 'Pendiente de revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
