import { StyleSheet } from 'react-native';
import { ThemeColors, SPACING, RADIUS } from '../constants/theme';

export const getStyles = (colors: ThemeColors) => StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    title: { fontSize: 24, fontWeight: '900', color: colors.text, marginBottom: 4 },
    subtitle: { fontSize: 14, color: colors.textLight, fontWeight: '600' },
    content: { padding: SPACING.lg },
    sectionTitle: { fontSize: 18, fontWeight: '800', marginBottom: SPACING.md, color: colors.text },
    workerCard: {
        marginBottom: SPACING.md,
        padding: SPACING.md,
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.smd,
    },
    workerInfo: { flex: 1 },
    workerName: { fontSize: 16, fontWeight: '700', color: colors.text },
    workerEmail: { fontSize: 13, color: colors.textLight },
    badge: {
        paddingHorizontal: SPACING.sm,
        paddingVertical: SPACING.xs,
        borderRadius: RADIUS.md,
        backgroundColor: colors.warning + '20',
    },
    badgeText: { fontSize: 10, fontWeight: '800', color: colors.warning, textTransform: 'uppercase' },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.8)', justifyContent: 'center', padding: 20 },
    modalContent: { backgroundColor: colors.surface, borderRadius: 24, padding: 0, maxHeight: '90%', overflow: 'hidden' },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: SPACING.lg,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    modalTitle: { fontSize: 18, fontWeight: '900', color: colors.text },
    modalBody: { padding: SPACING.lg },
    docCard: {
        backgroundColor: colors.background,
        borderRadius: RADIUS.xl,
        padding: SPACING.smd,
        marginBottom: SPACING.lg,
        borderWidth: 1,
        borderColor: colors.border,
    },
    docLabel: { fontSize: 11, fontWeight: '800', color: colors.textLight, marginBottom: SPACING.smd, textTransform: 'uppercase', letterSpacing: 0.5 },
    docImage: { width: '100%', height: 260, borderRadius: RADIUS.lg, backgroundColor: colors.surface },
    input: {
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: RADIUS.lg,
        padding: SPACING.smd,
        minHeight: 80,
        color: colors.text,
        textAlignVertical: 'top',
        marginBottom: SPACING.lg,
    },
});
