# Generated by Django 6.0.2 on 2026-03-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('NO_SHOW', 'Inasistencia'), ('DELAY', 'Retraso'), ('QUALITY', 'Calidad del servicio'), ('SAFETY', 'Seguridad'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_REVIEW', 'En revisión'), ('RESOLVED', 'Resuelto'), ('DISMISSED', 'Desestimado')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
