# Generated by Django 6.0.2 on 2026-04-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='escalation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='needs_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('IN_REVIEW', 'En revisión'), ('ESCALATED', 'Escalado'), ('RESOLVED', 'Resuelto'), ('DISMISSED', 'Desestimado')], default='OPEN', max_length=20),
        ),
    ]
